inputs_def:
  - handle: audio_files
    description: Input
    json_schema:
      type: array
      items:
        type: string
  - handle: name
    json_schema:
      type: string
    value:
    nullable: true
  - handle: format
    json_schema:
      enum:
        - mp3
      ui:options:
        labels:
          - MP3
    value:
    nullable: true
  - handle: save_address
    json_schema:
      type: string
      ui:widget: dir
    value:
    nullable: true
outputs_def:
  - handle: save_address
    description: Output
    json_schema:
      type: string
      ui:widget: file
ui:
  default_width: 450
executor:
  name: nodejs
  options:
    spawn: false
    entry: main.ts
title: Merged Audio
icon: ":carbon:audio-console:"
