inputs_def:
  - handle: video_source
    description: Input
    json_schema:
      type: string
      ui:widget: file
outputs_def:
  - handle: ffmpeg_source
    description: Output
    json_schema:
      contentMediaType: oomol/var
  - handle: file_address
    json_schema:
      type: string
      minLength: 1
      ui:widget: file
  - handle: file_name
    json_schema:
      type: string
icon: ":carbon:port-input:"
ui:
  default_width: 350
executor:
  name: nodejs
  options:
    spawn: false
    entry: main.ts
title: Read Media To FFmpeg
