executor:
  name: nodejs
  options:
    entry: main.ts
inputs_def:
  - handle: ffmpeg_source
    json_schema:
      contentMediaType: oomol/var
outputs_def:
  - handle: ffmpeg_source
    json_schema:
      contentMediaType: oomol/var
title: Mac Arm GPU
icon: ":twemoji:heart-on-fire:"
