executor:
  name: nodejs
  options:
    entry: main.ts
inputs_def:
  - handle: ffmpeg_source
    json_schema:
      contentMediaType: oomol/var
  - handle: encodeType
    json_schema:
      enum:
        - h264
        - hevc
      ui:options:
        labels:
          - h264
          - hevc
    value:
    nullable: true
outputs_def:
  - handle: ffmpeg_source
    json_schema:
      contentMediaType: oomol/var
title: Mac Arm GPU
icon: ":simple-icons:apple:"
