executor:
  name: nodejs
  options:
    entry: main.ts
inputs_def:
  - handle: input
    json_schema:
      type: string
outputs_def:
  - handle: output
    json_schema:
      type: string
title: Windows Nvidia
icon: ":twemoji:fire:"
