executor:
  name: nodejs
  options:
    entry: main.ts
inputs_def:
  - handle: ffmpeg_source
    json_schema:
      contentMediaType: oomol/var
  - handle: encodeType
    json_schema:
      enum:
        - h264
        - hevc
      ui:options:
        labels:
          - h264
          - hevc
    nullable: true
    value:
outputs_def:
  - handle: output
    json_schema:
      type: string
title: Windows Nvidia
icon: ":simple-icons:nvidia:"
