inputs_def:
  - handle: video_source
    description: Input
    json_schema:
      contentMediaType: oomol/var
    kind: video
  - handle: file_name
    json_schema:
      type: string
    value:
    nullable: true
  - handle: formate
    json_schema:
      enum:
        - mp4
        - wmv
        - mov
        - gif
        - flv
        - avi
      ui:options:
        labels:
          - MP4
          - WMV
          - MOV
          - GIF
          - FLV
          - AVI
    value:
    nullable: true
  - handle: save_address
    json_schema:
      type: string
      ui:widget: dir
    value:
    nullable: true
outputs_def:
  - handle: file_adress
    description: Output
    json_schema:
      type: string
      ui:widget: file
ui:
  default_width: 450
executor:
  name: nodejs
  options:
    spawn: false
    entry: main.ts
title: Save Video
icon: ":fa6-solid:file-video:"
